export const PARTI_CREATE = 'PARTICIPATION/CREATE';
export const PARTI_DELETE = 'PARTICIPATION/DELETE';
export const PARTI_CREATE_SUCCESS = 'PARTICIPATION/CREATE_SUCCESS';
export const PARTI_CREATE_FAIL = 'PARTICIPATION/CREATE_FAIL';
export const PARTI_DELETE_SUCCESS = 'PARTICIPATION/DELETE_SUCCESS';
export const PARTI_DELETE_FAIL = 'PARTICIPATION/DELETE_FAIL';

export const PARTI_JOIN_STATE = 'PARTICIPATION/JOIN_STATE';
export const PARTI_JOIN_STATE_SUCCESS = 'PARTICIPATION/PARTI_JOIN_STATE_SUCCESS';
export const PARTI_JOIN_STATE_FAIL = 'PARTICIPATION/PARTI_JOIN_STATE_FAIL';

export const PARTI_LIST = 'PARTICIPATION/LIST';
export const PARTI_LIST_SUCCESS = 'PARTICIPATION/LIST_SUCCESS';
export const PARTI_LIST_FAIL = 'PARTICIPATION/LIST_FAIL';

export const PARTI_JOIN_LIST = "PARTICIPATION/JOINT_LIST";
export const PARTI_JOIN_LIST_SUCCESS = "PARTICIPATION/JOIN_LIST_SUCCESS";
export const PARTI_JOIN_LIST_FAIL = "PARTICIPATION/JOIN_LIST_FAIL";
