export const QNA_CREATE = "QNA/CREATE";
export const QNA_CREATE_SUCCESS = "QNA/CREATE_SUCCESS";
export const QNA_CREATE_FAIL = "QNA/CREATE_FAIL";

export const QNA_UPDATE = "QNA/UPDATE_VALUE";
export const QNA_UPDATE_SUCCESS = "QNA/UPDATE_SUCCESS";
export const QNA_UPDATE_FAIL = "QNA/UPDATE_FAIL";

export const QNA_SELECT = "QNA/SELECT";
export const QNA_SELECT_SUCCESS = "QNA/SELECT_SUCCESS";
export const QNA_SELECT_FAIL = "QNA/SELECT_FAIL";

export const ANSWER_CREATE = "ANSWER/CREATE";
export const ANSWER_CREATE_SUCCESS = "ANSWER/CREATE_SUCCESS";
export const ANSWER_CREATE_FAIL = "ANSWER/CREATE_FAIL";
export const ANSWER_UPDATE_VALUE = "ANSWER/UPDATE_VALUE";

export const ANSWER_DELETE = "ANSWER/ANSWER_DELETE";
export const ANSWER_DELETE_SUCCESS = "ANSWER/DELETE_SUCCESS";
export const ANSWER_DELETE_FAIL = "ANSWER/DELETE_FAIL";

export const ANSWER_SELECT = "ANSWER/ANSER_SELECT";
export const ANSWER_TEMP = "ANSWER/ANSWER_TEMP";
