export const CREATE = "BOARD/CREATE";
export const CREATE_SUCCESS = "BOARD/CREATE_SUCCESS";
export const CREATE_FAIL = "BOARD/CREATE_FAIL";
export const UPDATE = "BOARD/UPDATE";
export const UPDATE_SUCCESS = "BOARD/UPDATE_SUCCESS";
export const UPDATE_FAIL = "BOARD/UPDATE_FAIL";
export const UPDATE_VALUE = "BOARD/UPDATE_VALUE";
export const READ_VALUE = "BOARD/READ_VALUE";
export const READ_SUCCESS = "BOARD/READ_SUCCESS";
export const READ_FAIL = "BOARD/READ_FAIL";

export const BOARD_POST = "MAINBOARD/BOARD_POST";
export const BOARD_POST_FAIL = "MAINBOARD/BOARD_POST_FAIL";
export const BOARD_POST_SUCCESS = "MAINBOARD/BOARD_POST_SUCCESS";

export const CATEGORY_POST = "CATEGORY/CATEGORY_POST";
export const CATEGORY_POST_FAIL = "CATEGORY/CATEGORY_POST_FAIL";
export const CATEGORY_POST_SUCCESS = "CATEGORY/CATEGORY_POST_SUCCESS";

export const INIT = "MAINBOARD/INIT";
