export const USER_CHECK = 'USER_CHECK';
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS';
export const USER_CHECK_FAIL = 'USER_CHECK_FAIL';

export const GET_BANK_ACCOUNT = "GET_BANK_ACCOUNT";
export const GET_BANK_ACCOUNT_SUCCESS = "GET_BANK_ACCOUNT_SUCCESS";
export const GET_BANK_ACCOUNT_FAIL = "GET_BANK_ACCOUNT_FAIL";
